### ISSUE TITLE
App Crashes on Request

### ISSUE THREAD

**Issue by robertmain** [Tarrask/sails-generate-new-webpack-vue#5]
After lifting my app crashes as soon as I make a request to it with the following error:

```
<my-app>\node_modules\webpack\lib\HotModuleReplacementPlugin.js:59
                                        records.chunkModuleIds[chunk.id] = chunk.mapModules(m => m.id);
                                                                                 ^

TypeError: chunk.mapModules is not a function
```

Here's the full stack trace:

```
TypeError: chunk.mapModules is not a function
    at chunks.forEach.chunk (<my-app>\node_modules\webpack\lib\HotModuleReplacementPlugin.js:59:47)
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (<my-app>\node_modules\webpack\lib\HotModuleReplacementPlugin.js:58:17)
    at Compilation.applyPlugins2 (<my-app>\node_modules\tapable\lib\Tapable.js:82:14)
    at sealPart2 (<my-app>\node_modules\sails-hook-webpack-vue\node_modules\webpack\lib\Compilation.js:629:10)
    at Compilation.applyPluginsAsyncSeries (<my-app>\node_modules\tapable\lib\Tapable.js:195:46)
    at Compilation.seal (<my-app>\node_modules\sails-hook-webpack-vue\node_modules\webpack\lib\Compilation.js:579:8)
    at <my-app>\node_modules\sails-hook-webpack-vue\node_modules\webpack\lib\Compiler.js:493:16
    at <my-app>\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (<my-app>\node_modules\sails-hook-webpack-vue\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (<my-app>\node_modules\sails-hook-webpack-vue\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by Tarrask** [comment]
What webpack version are you using ? Version 3 ?

What is strange is that sometime it use the webpack module from `<my-app>\node_modules\webpack\` and at other place, one installed in `<my-app>\node_modules\sails-hook-webpack-vue\node_modules\webpack\`.

**Comment by Tarrask** [comment]
Should be fixed with commit Tarrask/sails-hook-webpack-vue@dfda4638cc4b00a96b47208fefb944d97e94744a webpack is now a peer dependency and should no more pull a different version just for this module.
